#!/usr/bin/env python3
"""
Migration: Add Community Meals Support
- Enables users to add custom meals
- Tracks meal origin (system vs user-created)
- Allows public/private sharing
"""

import sys
sys.path.insert(0, '.')

from flask_app.db import execute_query

def migrate():
    try:
        print("🔄 Starting Community Meals Migration...")
        
        # 1. Add user_created column to meals table
        print("\n1️⃣ Adding user creation tracking...")
        execute_query("""
            ALTER TABLE meals
            ADD COLUMN IF NOT EXISTS created_by_user_id INTEGER,
            ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT true,
            ADD COLUMN IF NOT EXISTS date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT false
        """, fetch=False)
        print("✅ Columns added: created_by_user_id, is_public, date_created, is_verified")
        
        # 2. Create meal_favorites table
        print("\n2️⃣ Creating meal favorites table...")
        execute_query("""
            CREATE TABLE IF NOT EXISTS meal_favorites (
                favorite_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL,
                meal_id INTEGER NOT NULL,
                date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_fav_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
                CONSTRAINT fk_fav_meal FOREIGN KEY (meal_id) REFERENCES meals(meal_id) ON DELETE CASCADE,
                CONSTRAINT uq_fav_unique UNIQUE (user_id, meal_id)
            )
        """, fetch=False)
        print("✅ meal_favorites table created")
        
        # 3. Create meal_history table (for recently used)
        print("\n3️⃣ Creating meal history table...")
        execute_query("""
            CREATE TABLE IF NOT EXISTS meal_history (
                history_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id INTEGER NOT NULL,
                meal_id INTEGER NOT NULL,
                last_used TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                use_count INTEGER DEFAULT 1,
                CONSTRAINT fk_hist_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
                CONSTRAINT fk_hist_meal FOREIGN KEY (meal_id) REFERENCES meals(meal_id) ON DELETE CASCADE,
                CONSTRAINT uq_hist_unique UNIQUE (user_id, meal_id)
            )
        """, fetch=False)
        print("✅ meal_history table created")
        
        # 4. Verify system meals are marked as verified and public
        print("\n4️⃣ Updating system meals...")
        execute_query("""
            UPDATE meals 
            SET is_verified = true, 
                created_by_user_id = 0
            WHERE created_by_user_id IS NULL
        """, fetch=False)
        print("✅ System meals verified")
        
        print("\n✅ Migration Complete! Community meals system ready.")
        print("   - Users can now add custom meals")
        print("   - Meals tracked: favorites, history, public/private")
        
    except Exception as e:
        print(f"❌ Migration failed: {e}")
        return False
    
    return True

if __name__ == '__main__':
    success = migrate()
    sys.exit(0 if success else 1)
