#!/usr/bin/env python3
"""
Smart Diet Planner - Community Activities Migration
Enables user-created activities and activity favorites tracking
Run: python migrate_community_activities.py
"""

import psycopg2
from psycopg2 import sql
import sys

# Database connection details
DB_CONFIG = {
    'host': 'localhost',
    'database': 'smart_diet_planner',
    'user': 'postgres',
    'password': 'password'
}

def run_migration():
    """Execute the migration to add community activities support"""
    try:
        conn = psycopg2.connect(**DB_CONFIG)
        cursor = conn.cursor()
        
        print("🔄 Starting Activities Migration...")
        
        # ============================================================================
        # Step 1: Extend ACTIVITIES table with community features
        # ============================================================================
        print("\n📝 Step 1: Adding columns to ACTIVITIES table...")
        
        # Check and add met_value column
        cursor.execute("""
            SELECT column_name FROM information_schema.columns 
            WHERE table_name = 'activities' AND column_name = 'met_value'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE activities ADD COLUMN met_value NUMERIC(4,2) DEFAULT 1.0 CHECK (met_value > 0)
            """)
            print("   ✓ Added met_value column (for accurate calorie calculation)")
        else:
            print("   ⊙ met_value column already exists")
        
        # Check and add created_by_user_id
        cursor.execute("""
            SELECT column_name FROM information_schema.columns 
            WHERE table_name = 'activities' AND column_name = 'created_by_user_id'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE activities ADD COLUMN created_by_user_id INTEGER DEFAULT 0
            """)
            print("   ✓ Added created_by_user_id column (0 = system, user_id = custom)")
        else:
            print("   ⊙ created_by_user_id column already exists")
        
        # Check and add is_public
        cursor.execute("""
            SELECT column_name FROM information_schema.columns 
            WHERE table_name = 'activities' AND column_name = 'is_public'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE activities ADD COLUMN is_public BOOLEAN DEFAULT true
            """)
            print("   ✓ Added is_public column (true = visible to all users)")
        else:
            print("   ⊙ is_public column already exists")
        
        # Check and add is_verified
        cursor.execute("""
            SELECT column_name FROM information_schema.columns 
            WHERE table_name = 'activities' AND column_name = 'is_verified'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE activities ADD COLUMN is_verified BOOLEAN DEFAULT false
            """)
            print("   ✓ Added is_verified column (false = user-created)")
        else:
            print("   ⊙ is_verified column already exists")
        
        # Check and add date_created
        cursor.execute("""
            SELECT column_name FROM information_schema.columns 
            WHERE table_name = 'activities' AND column_name = 'date_created'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                ALTER TABLE activities ADD COLUMN date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            """)
            print("   ✓ Added date_created column")
        else:
            print("   ⊙ date_created column already exists")
        
        conn.commit()
        
        # ============================================================================
        # Step 2: Create ACTIVITY_FAVORITES table
        # ============================================================================
        print("\n📝 Step 2: Creating activity_favorites table...")
        
        cursor.execute("""
            SELECT table_name FROM information_schema.tables 
            WHERE table_name = 'activity_favorites'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                CREATE TABLE activity_favorites (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                    user_id INTEGER NOT NULL,
                    activity_id INTEGER NOT NULL,
                    date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT pk_activity_favorites PRIMARY KEY (id),
                    CONSTRAINT fk_activity_favorites_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
                    CONSTRAINT fk_activity_favorites_activity FOREIGN KEY (activity_id) REFERENCES activities(activity_id) ON DELETE CASCADE,
                    CONSTRAINT uq_activity_favorites UNIQUE (user_id, activity_id)
                )
            """)
            print("   ✓ Created activity_favorites table")
        else:
            print("   ⊙ activity_favorites table already exists")
        
        conn.commit()
        
        # ============================================================================
        # Step 3: Create ACTIVITY_HISTORY table
        # ============================================================================
        print("\n📝 Step 3: Creating activity_history table...")
        
        cursor.execute("""
            SELECT table_name FROM information_schema.tables 
            WHERE table_name = 'activity_history'
        """)
        if not cursor.fetchone():
            cursor.execute("""
                CREATE TABLE activity_history (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                    user_id INTEGER NOT NULL,
                    activity_id INTEGER NOT NULL,
                    last_used TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    use_count INTEGER DEFAULT 1,
                    CONSTRAINT pk_activity_history PRIMARY KEY (id),
                    CONSTRAINT fk_activity_history_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
                    CONSTRAINT fk_activity_history_activity FOREIGN KEY (activity_id) REFERENCES activities(activity_id) ON DELETE CASCADE,
                    CONSTRAINT uq_activity_history UNIQUE (user_id, activity_id)
                )
            """)
            print("   ✓ Created activity_history table")
        else:
            print("   ⊙ activity_history table already exists")
        
        conn.commit()
        
        # ============================================================================
        # Step 4: Mark system activities as verified
        # ============================================================================
        print("\n📝 Step 4: Marking system activities as verified...")
        
        cursor.execute("""
            UPDATE activities SET is_verified = true, created_by_user_id = 0 
            WHERE created_by_user_id = 0 OR created_by_user_id IS NULL
        """)
        updated_count = cursor.rowcount
        print(f"   ✓ Marked {updated_count} system activities as verified")
        
        conn.commit()
        
        # ============================================================================
        # Step 5: Update MET values for common activities
        # ============================================================================
        print("\n📝 Step 5: Updating MET values for common activities...")
        
        met_values = {
            'Running': 9.8,
            'Walking': 3.5,
            'Cycling': 7.5,
            'Weight Lifting': 6.0,
            'Push-ups': 8.0,
            'Yoga': 2.5,
            'Stretching': 2.3,
            'Swimming': 10.0,
            'Jogging': 7.0,
            'HIIT': 12.0,
            'Dancing': 7.0,
            'Basketball': 8.0,
            'Tennis': 7.3,
            'Soccer': 9.5,
        }
        
        for activity_name, met in met_values.items():
            cursor.execute("""
                UPDATE activities SET met_value = %s 
                WHERE LOWER(activity_name) = LOWER(%s)
            """, (met, activity_name))
        
        print(f"   ✓ Updated MET values for {len(met_values)} activities")
        
        conn.commit()
        
        # ============================================================================
        # Final Summary
        # ============================================================================
        cursor.execute("SELECT COUNT(*) FROM activities WHERE is_verified = true")
        verified_count = cursor.fetchone()[0]
        
        cursor.execute("SELECT COUNT(*) FROM activities WHERE is_verified = false")
        custom_count = cursor.fetchone()[0]
        
        print("\n" + "="*70)
        print("✅ MIGRATION COMPLETE!")
        print("="*70)
        print(f"📊 Database Statistics:")
        print(f"   • System Activities (verified): {verified_count}")
        print(f"   • User Activities (custom): {custom_count}")
        print(f"   • Favorite Activities: Tracking enabled")
        print(f"   • Activity History: Tracking enabled")
        print("\n🎯 Features Now Available:")
        print("   ✓ User-created activities")
        print("   ✓ MET-based calorie calculation")
        print("   ✓ Activity favorites")
        print("   ✓ Activity history tracking")
        print("   ✓ Community activities support")
        print("="*70)
        
        cursor.close()
        conn.close()
        
        return True
        
    except psycopg2.Error as e:
        print(f"\n❌ Database Error: {e}")
        print(f"Error Code: {e.pgcode}")
        return False
    except Exception as e:
        print(f"\n❌ Unexpected Error: {e}")
        return False

if __name__ == '__main__':
    success = run_migration()
    sys.exit(0 if success else 1)
