-- ============================================================================
-- Smart Diet & Lifestyle Planner - Table Creation Script
-- PostgreSQL Schema Definition
-- Run with: psql -U postgres -d smart_diet_planner -f create_tables.sql
-- ============================================================================

-- Drop existing tables safely (reverse FK order)
DROP TABLE IF EXISTS MOOD_LOG       CASCADE;
DROP TABLE IF EXISTS ACTIVITY_LOG   CASCADE;
DROP TABLE IF EXISTS MEAL_LOG       CASCADE;
DROP TABLE IF EXISTS REPORTS        CASCADE;
DROP TABLE IF EXISTS SUGGESTIONS    CASCADE;
DROP TABLE IF EXISTS GOALS          CASCADE;
DROP TABLE IF EXISTS DAILY_LOG      CASCADE;
DROP TABLE IF EXISTS ACTIVITIES     CASCADE;
DROP TABLE IF EXISTS MEALS          CASCADE;
DROP TABLE IF EXISTS USERS          CASCADE;

-- ============================================================================
-- Table 1: USERS
-- ============================================================================
CREATE TABLE USERS (
    user_id            INTEGER GENERATED BY DEFAULT AS IDENTITY,
    username           VARCHAR(50)  NOT NULL,
    email              VARCHAR(100) NOT NULL,
    password_hash      VARCHAR(255) NOT NULL,
    first_name         VARCHAR(50),
    last_name          VARCHAR(50),
    date_of_birth      DATE,
    gender             VARCHAR(10)  CHECK (gender IN ('Male', 'Female', 'Other')),
    weight             NUMERIC(5,2) CHECK (weight > 0),
    height             NUMERIC(5,2) CHECK (height > 0),
    activity_level     VARCHAR(20)  CHECK (activity_level IN ('Sedentary', 'Light', 'Moderate', 'Active', 'Very Active')),
    dietary_preference VARCHAR(50),
    health_condition   VARCHAR(255),
    created_date       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users           PRIMARY KEY (user_id),
    CONSTRAINT uq_users_username  UNIQUE (username),
    CONSTRAINT uq_users_email     UNIQUE (email)
);

-- ============================================================================
-- Table 2: GOALS
-- ============================================================================
CREATE TABLE GOALS (
    goal_id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id       INTEGER      NOT NULL,
    goal_type     VARCHAR(50)  NOT NULL CHECK (goal_type IN ('Weight Loss', 'Weight Gain', 'Maintain Weight', 'Muscle Gain', 'Fitness')),
    target_value  NUMERIC(6,2) CHECK (target_value > 0),
    current_value NUMERIC(6,2),
    start_date    DATE         DEFAULT CURRENT_DATE,
    target_date   DATE,
    status        VARCHAR(20)  DEFAULT 'Active' CHECK (status IN ('Active', 'Completed', 'Cancelled')),
    created_date  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_goals      PRIMARY KEY (goal_id),
    CONSTRAINT fk_goals_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_goals_dates CHECK (target_date >= start_date)
);

-- ============================================================================
-- Table 3: MEALS
-- ============================================================================
CREATE TABLE MEALS (
    meal_id       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    meal_name     VARCHAR(100) NOT NULL,
    meal_category VARCHAR(50)  CHECK (meal_category IN ('Breakfast', 'Lunch', 'Dinner', 'Snack', 'Beverage')),
    calories      NUMERIC(6,2) CHECK (calories >= 0),
    protein       NUMERIC(6,2) DEFAULT 0 CHECK (protein >= 0),
    carbohydrates NUMERIC(6,2) DEFAULT 0 CHECK (carbohydrates >= 0),
    fats          NUMERIC(6,2) DEFAULT 0 CHECK (fats >= 0),
    fiber         NUMERIC(6,2) DEFAULT 0 CHECK (fiber >= 0),
    serving_size  VARCHAR(50),
    description   VARCHAR(255),
    CONSTRAINT pk_meals      PRIMARY KEY (meal_id),
    CONSTRAINT uq_meals_name UNIQUE (meal_name)
);

-- ============================================================================
-- Table 4: ACTIVITIES
-- ============================================================================
CREATE TABLE ACTIVITIES (
    activity_id        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    activity_name      VARCHAR(100) NOT NULL,
    activity_category  VARCHAR(50)  CHECK (activity_category IN ('Cardio', 'Strength', 'Flexibility', 'Sports', 'HIIT', 'Other')),
    calories_per_minute NUMERIC(5,2) CHECK (calories_per_minute >= 0),
    intensity_level    VARCHAR(20)  CHECK (intensity_level IN ('Low', 'Moderate', 'High', 'Very High')),
    description        VARCHAR(255),
    CONSTRAINT pk_activities      PRIMARY KEY (activity_id),
    CONSTRAINT uq_activities_name UNIQUE (activity_name)
);

-- ============================================================================
-- Table 5: DAILY_LOG
-- ============================================================================
CREATE TABLE DAILY_LOG (
    daily_log_id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id                  INTEGER      NOT NULL,
    log_date                 DATE         NOT NULL,
    total_calories_consumed  NUMERIC(6,2) DEFAULT 0 CHECK (total_calories_consumed >= 0),
    total_calories_burned    NUMERIC(6,2) DEFAULT 0 CHECK (total_calories_burned >= 0),
    water_intake             NUMERIC(5,2) DEFAULT 0 CHECK (water_intake >= 0),
    sleep_hours              NUMERIC(4,2) CHECK (sleep_hours >= 0 AND sleep_hours <= 24),
    weight                   NUMERIC(5,2) CHECK (weight > 0),
    notes                    VARCHAR(500),
    created_date             TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_daily_log             PRIMARY KEY (daily_log_id),
    CONSTRAINT fk_daily_log_user        FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_daily_log_user_date   UNIQUE (user_id, log_date)
);

-- ============================================================================
-- Table 6: MEAL_LOG
-- ============================================================================
CREATE TABLE MEAL_LOG (
    meal_log_id    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    daily_log_id   INTEGER      NOT NULL,
    meal_id        INTEGER      NOT NULL,
    meal_time      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    quantity       NUMERIC(6,2) DEFAULT 1 CHECK (quantity > 0),
    total_calories NUMERIC(6,2) CHECK (total_calories >= 0),
    notes          VARCHAR(255),
    CONSTRAINT pk_meal_log       PRIMARY KEY (meal_log_id),
    CONSTRAINT fk_meal_log_daily FOREIGN KEY (daily_log_id) REFERENCES DAILY_LOG(daily_log_id) ON DELETE CASCADE,
    CONSTRAINT fk_meal_log_meal  FOREIGN KEY (meal_id) REFERENCES MEALS(meal_id)
);

-- ============================================================================
-- Table 7: ACTIVITY_LOG
-- ============================================================================
CREATE TABLE ACTIVITY_LOG (
    activity_log_id  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    daily_log_id     INTEGER      NOT NULL,
    activity_id      INTEGER      NOT NULL,
    duration_minutes NUMERIC(6,2) NOT NULL CHECK (duration_minutes > 0),
    calories_burned  NUMERIC(6,2) CHECK (calories_burned >= 0),
    activity_time    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    notes            VARCHAR(255),
    CONSTRAINT pk_activity_log          PRIMARY KEY (activity_log_id),
    CONSTRAINT fk_activity_log_daily    FOREIGN KEY (daily_log_id) REFERENCES DAILY_LOG(daily_log_id) ON DELETE CASCADE,
    CONSTRAINT fk_activity_log_activity FOREIGN KEY (activity_id) REFERENCES ACTIVITIES(activity_id)
);

-- ============================================================================
-- Table 8: MOOD_LOG
-- ============================================================================
CREATE TABLE MOOD_LOG (
    mood_log_id  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    daily_log_id INTEGER     NOT NULL,
    mood_rating  SMALLINT    NOT NULL CHECK (mood_rating BETWEEN 1 AND 5),
    stress_level VARCHAR(20) CHECK (stress_level IN ('Low', 'Moderate', 'High')),
    energy_level VARCHAR(20) CHECK (energy_level IN ('Low', 'Moderate', 'High')),
    notes        VARCHAR(500),
    log_time     TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_mood_log       PRIMARY KEY (mood_log_id),
    CONSTRAINT fk_mood_log_daily FOREIGN KEY (daily_log_id) REFERENCES DAILY_LOG(daily_log_id) ON DELETE CASCADE
);

-- ============================================================================
-- Table 9: SUGGESTIONS
-- ============================================================================
CREATE TABLE SUGGESTIONS (
    suggestion_id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id                INTEGER       NOT NULL,
    suggestion_type        VARCHAR(50)   NOT NULL CHECK (suggestion_type IN ('Diet', 'Exercise', 'Lifestyle', 'Health')),
    suggestion_text        VARCHAR(1000) NOT NULL,
    reasoning              VARCHAR(1000),
    reasoning_explanation  VARCHAR(4000),
    ai_confidence          NUMERIC(3,2),
    reasoning_type         VARCHAR(100),
    priority               VARCHAR(20)   DEFAULT 'Medium' CHECK (priority IN ('Low', 'Medium', 'High')),
    status                 VARCHAR(20)   DEFAULT 'Pending' CHECK (status IN ('Pending', 'Accepted', 'Rejected', 'Completed')),
    created_date           TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_suggestions      PRIMARY KEY (suggestion_id),
    CONSTRAINT fk_suggestions_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);

-- ============================================================================
-- Table 10: REPORTS
-- ============================================================================
CREATE TABLE REPORTS (
    report_id               INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id                 INTEGER      NOT NULL,
    report_type             VARCHAR(50)  NOT NULL CHECK (report_type IN ('Weekly', 'Monthly', 'Custom')),
    report_period_start     DATE         NOT NULL,
    report_period_end       DATE         NOT NULL,
    total_calories_consumed NUMERIC(8,2),
    total_calories_burned   NUMERIC(8,2),
    average_weight          NUMERIC(5,2),
    weight_change           NUMERIC(5,2),
    goals_achieved          SMALLINT,
    report_summary          VARCHAR(2000),
    generated_date          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_reports      PRIMARY KEY (report_id),
    CONSTRAINT fk_reports_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_reports_dates CHECK (report_period_end >= report_period_start)
);

\echo 'Schema created successfully.'
