-- ============================================================================
-- Smart Diet & Lifestyle Planner - Table Creation Script
-- Oracle SQL Schema Definition
-- ============================================================================

-- ============================================================================
-- Table 1: USERS
-- Purpose: Stores user account and profile information
-- ============================================================================
SHOW CON_NAME; --to check current container
ALTER SESSION SET CONTAINER = XEPDB1; --to shift to the pluggable database
ALTER SESSION SET CONTAINER = CDB$ROOT; --to shift to the root container
CREATE TABLE USERS (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    date_of_birth DATE,
    gender VARCHAR2(10) CHECK (gender IN ('Male', 'Female', 'Other')),
    weight NUMBER(5,2) CHECK (weight > 0),
    height NUMBER(5,2) CHECK (height > 0),
    activity_level VARCHAR2(20) CHECK (activity_level IN ('Sedentary', 'Light', 'Moderate', 'Active', 'Very Active')),
    dietary_preference VARCHAR2(50),
    health_condition VARCHAR2(255),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- Table 2: GOALS
-- Purpose: Stores user health and fitness goals
-- ============================================================================
CREATE TABLE GOALS (
    goal_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    goal_type VARCHAR2(50) NOT NULL CHECK (goal_type IN ('Weight Loss', 'Weight Gain', 'Maintain Weight', 'Muscle Gain', 'Fitness')),
    target_value NUMBER(6,2) CHECK (target_value > 0),
    current_value NUMBER(6,2),
    start_date DATE DEFAULT SYSDATE,
    target_date DATE,
    status VARCHAR2(20) DEFAULT 'Active' CHECK (status IN ('Active', 'Completed', 'Cancelled')),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_goals PRIMARY KEY (goal_id),
    CONSTRAINT fk_goals_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_goals_dates CHECK (target_date >= start_date)
);

-- ============================================================================
-- Table 3: MEALS
-- Purpose: Master table for meal types and nutritional information
-- ============================================================================
CREATE TABLE MEALS (
    meal_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    meal_name VARCHAR2(100) NOT NULL,
    meal_category VARCHAR2(50) CHECK (meal_category IN ('Breakfast', 'Lunch', 'Dinner', 'Snack')),
    calories NUMBER(6,2) CHECK (calories >= 0),
    protein NUMBER(6,2) DEFAULT 0 CHECK (protein >= 0),
    carbohydrates NUMBER(6,2) DEFAULT 0 CHECK (carbohydrates >= 0),
    fats NUMBER(6,2) DEFAULT 0 CHECK (fats >= 0),
    fiber NUMBER(6,2) DEFAULT 0 CHECK (fiber >= 0),
    serving_size VARCHAR2(50),
    description VARCHAR2(255),
    CONSTRAINT pk_meals PRIMARY KEY (meal_id),
    CONSTRAINT uq_meals_name UNIQUE (meal_name)
);

-- ============================================================================
-- Table 4: ACTIVITIES
-- Purpose: Master table for physical activities and calorie burn rates
-- ============================================================================
CREATE TABLE ACTIVITIES (
    activity_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    activity_name VARCHAR2(100) NOT NULL,
    activity_category VARCHAR2(50) CHECK (activity_category IN ('Cardio', 'Strength', 'Flexibility', 'Sports', 'Other')),
    calories_per_minute NUMBER(5,2) CHECK (calories_per_minute >= 0),
    intensity_level VARCHAR2(20) CHECK (intensity_level IN ('Low', 'Moderate', 'High', 'Very High')),
    description VARCHAR2(255),
    CONSTRAINT pk_activities PRIMARY KEY (activity_id),
    CONSTRAINT uq_activities_name UNIQUE (activity_name)
);

-- ============================================================================
-- Table 5: DAILY_LOG
-- Purpose: Stores daily summary logs for each user
-- ============================================================================
CREATE TABLE DAILY_LOG (
    daily_log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    log_date DATE NOT NULL,
    total_calories_consumed NUMBER(6,2) DEFAULT 0 CHECK (total_calories_consumed >= 0),
    total_calories_burned NUMBER(6,2) DEFAULT 0 CHECK (total_calories_burned >= 0),
    water_intake NUMBER(5,2) DEFAULT 0 CHECK (water_intake >= 0),
    sleep_hours NUMBER(4,2) CHECK (sleep_hours >= 0 AND sleep_hours <= 24),
    weight NUMBER(5,2) CHECK (weight > 0),
    notes VARCHAR2(500),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_daily_log PRIMARY KEY (daily_log_id),
    CONSTRAINT fk_daily_log_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT uq_daily_log_user_date UNIQUE (user_id, log_date)
);

-- ============================================================================
-- Table 6: MEAL_LOG
-- Purpose: Stores individual meal entries linked to daily logs
-- ============================================================================
CREATE TABLE MEAL_LOG (
    meal_log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    daily_log_id NUMBER NOT NULL,
    meal_id NUMBER NOT NULL,
    meal_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    quantity NUMBER(6,2) DEFAULT 1 CHECK (quantity > 0),
    total_calories NUMBER(6,2) CHECK (total_calories >= 0),
    notes VARCHAR2(255),
    CONSTRAINT pk_meal_log PRIMARY KEY (meal_log_id),
    CONSTRAINT fk_meal_log_daily FOREIGN KEY (daily_log_id) REFERENCES DAILY_LOG(daily_log_id) ON DELETE CASCADE,
    CONSTRAINT fk_meal_log_meal FOREIGN KEY (meal_id) REFERENCES MEALS(meal_id)
);

-- ============================================================================
-- Table 7: ACTIVITY_LOG
-- Purpose: Stores individual activity entries linked to daily logs
-- ============================================================================
CREATE TABLE ACTIVITY_LOG (
    activity_log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    daily_log_id NUMBER NOT NULL,
    activity_id NUMBER NOT NULL,
    duration_minutes NUMBER(6,2) NOT NULL CHECK (duration_minutes > 0),
    calories_burned NUMBER(6,2) CHECK (calories_burned >= 0),
    activity_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    notes VARCHAR2(255),
    CONSTRAINT pk_activity_log PRIMARY KEY (activity_log_id),
    CONSTRAINT fk_activity_log_daily FOREIGN KEY (daily_log_id) REFERENCES DAILY_LOG(daily_log_id) ON DELETE CASCADE,
    CONSTRAINT fk_activity_log_activity FOREIGN KEY (activity_id) REFERENCES ACTIVITIES(activity_id)
);

-- ============================================================================
-- Table 8: MOOD_LOG
-- Purpose: Tracks user mood and mental wellness
-- ============================================================================
CREATE TABLE MOOD_LOG (
    mood_log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    daily_log_id NUMBER NOT NULL,
    mood_rating NUMBER(1) NOT NULL CHECK (mood_rating BETWEEN 1 AND 5),
    stress_level VARCHAR2(20) CHECK (stress_level IN ('Low', 'Moderate', 'High')),
    energy_level VARCHAR2(20) CHECK (energy_level IN ('Low', 'Moderate', 'High')),
    notes VARCHAR2(500),
    log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_mood_log PRIMARY KEY (mood_log_id),
    CONSTRAINT fk_mood_log_daily FOREIGN KEY (daily_log_id) REFERENCES DAILY_LOG(daily_log_id) ON DELETE CASCADE
);

-- ============================================================================
-- Table 9: SUGGESTIONS
-- Purpose: Stores AI-generated suggestions and recommendations
-- ============================================================================
CREATE TABLE SUGGESTIONS (
    suggestion_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    suggestion_type VARCHAR2(50) NOT NULL CHECK (suggestion_type IN ('Diet', 'Exercise', 'Lifestyle', 'Health')),
    suggestion_text VARCHAR2(1000) NOT NULL,
    reasoning VARCHAR2(1000),
    priority VARCHAR2(20) DEFAULT 'Medium' CHECK (priority IN ('Low', 'Medium', 'High')),
    status VARCHAR2(20) DEFAULT 'Pending' CHECK (status IN ('Pending', 'Accepted', 'Rejected', 'Completed')),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_suggestions PRIMARY KEY (suggestion_id),
    CONSTRAINT fk_suggestions_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);

-- ============================================================================
-- Table 10: REPORTS
-- Purpose: Stores generated health and progress reports
-- ============================================================================
CREATE TABLE REPORTS (
    report_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    report_type VARCHAR2(50) NOT NULL CHECK (report_type IN ('Weekly', 'Monthly', 'Custom')),
    report_period_start DATE NOT NULL,
    report_period_end DATE NOT NULL,
    total_calories_consumed NUMBER(8,2),
    total_calories_burned NUMBER(8,2),
    average_weight NUMBER(5,2),
    weight_change NUMBER(5,2),
    goals_achieved NUMBER(3),
    report_summary VARCHAR2(2000),
    generated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_reports PRIMARY KEY (report_id),
    CONSTRAINT fk_reports_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    CONSTRAINT chk_reports_dates CHECK (report_period_end >= report_period_start)
);
